# Site settings
title: Tanaka Chingonzo
description: Curating stories of Progress by Tanaka Chingonzo
author: Tanaka Chingonzo
email: tanaka.chingonzo@watsonuniversity.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tanaka.co.zw" # the base hostname & protocol for your site
twitter_username: tanakachingonzo
github_username:  tanakachingonzo
facebook_username: tanaka.ching


# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title
sass:
    style: compressed
