# main text of home
name: Tanaka Chingonzo
bio: Making Connections between people and data
author: Tanaka Chingonzo

# your url: http://USERNAME.github.io
url: http://tanaka.co.zw/

# twitter summary info
description: Digital Humanities Student writing about Computer Science and the Humanities

picture: assets/images/picture.jpg


# if you don't have any of social below, comment the line
facebook: tanakachingonzo

twitter:
  username: tanakachingonzo
  card: summary

github: tanakachingonzo
email: tchingonzo21(at)wooster.edu
linkedin: tanakachingonzo

webmaster_verifications:
  google: n9cECzXDz-nT9u9E2Rx0tTilceSX692q1wJAIBAdogY
  bing: B9D9DC6DCEBA8821431AA3336C5A1512

plugins:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
