# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, _images, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile, Gemfile.lock]
permalink:            /:title/
compress_html:
  clippings: all
  comments: all


# Site meta
title:                'Tanaka Chingonzo'
tagline:              'Life Long Learner'
description:          'I am a passionate learner and problem solver. <a href="http://tanaka.co.zw/blog/" target="_blank" rel="noopener noreferrer">So I made this</a>.'
keywords:             'tanaka, chingonzo, tanakachingonzo, developer, traveller, design, code, jekyll, change, theme, for hire'
url:                  http://tanaka.co.zw
baseurl:              
assets:               /assets
images:               /images/
image:                index-large.jpg
logo:                 /assets/icons/apple-icon-144x144.png
dark_theme:           false

author:
  name:               Tanaka Chingonzo
  bio:                Hi, I'm Tanaka, the author of this blog. Nice to meet you!
  image:              author
  url:                http://tanaka.co.zw
  email:              tanaka.chingonzo@watsonuniversity.org
  twitter:            tanakachingonzo

social:
  twitter:            https://twitter.com/tanakachingonzo
  instagram:          https://instagram.com/tanakachingonzo
  github:             https://github.com/tanakachingonzo
  medium:             https://medium.com
version:              3.1.3

github:
  repo:               https://github.com/tanakachingonzo/tanakachingonzo.github.io.git


# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass:           400, 600, 800

google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM


# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/tanakachingonzo/