#
###################################
# Site wide configuration
####################################
#
title: Tanaka Chingonzo
email: tchingonzo21@wooster.edu
description: Tanaka Chingonzo a global shaper with the World Economic Forum, and a student from Zimbabwe. He is a software engineer and student in Ohio.
url: http://tanaka.co.zw # the base hostname & protocol for your site
keywords: ["Programming", "Python", "C", "Entrepreneur"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Tanaka Chingonzo
  avatar: tanaka-chingonzo.png
  job: "Python & C programmer. Web Developer."
  bio: "Tanaka Chingonzo a global shaper with the World Economic Forum, and a student from Zimbabwe. He is a software engineer and student in Ohio."
  email: tchingonzo21@wooster.edu
  disqus-shortname: tanakachingonzo
  twitter: tanakachingonzo #username
  facebook: tanakachingonzo #username
  google:
    plus: tanakachingonzo #username
    analytics: UA-83940835-1
    verify: <meta name="google-site-verification" content="n9cECzXDz-nT9u9E2Rx0tTilceSX692q1wJAIBAdogY" />
    ad-client:
    ad-slot:
  bing-verify: <meta name="msvalidate.01" content="DF6EFA3DFDBFF0D4F3AAD9B490C1D9A2" />
  github: tanakachingonzo #username
  stackoverflow: 6148490/tanaka-chingonzo   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: tanakachingonzo #username
  xing: #username
  instagram: tanakachingonzo #username
  lastfm: #username
  tumblr: #username
  pinterest: tanakachingonzo #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: UCT5v02qriBiFiUt3hD5s0xw#username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
